apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-hello-world
  name: node-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world
  strategy: {}
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
      - image: prajyotparab31904/node-hello-world:latest
        imagePullPolicy: Always
        name: node-hello-world
        volumeMounts:
          - name: sample-secret-apikey
            mountPath: /sample-secret/apikey
          - name: sample-secret-cert
            mountPath: /sample-secret/cert
        resources:
         requests:
          cpu: 100m
          memory: 128Mi
         limits:
          cpu: 200m
          memory: 256Mi
      volumes:
      - name: sample-secret-apikey
        secret:
          secretName: sample-secret-apikey
      - name: sample-secret-cert
        secret:
          secretName: sample-secret-cert
status: {}
